export const INCREASE_ITEM = "INCREASE_ITEM"
export const DECREASE_ITEM = "DECREASE_ITEM"
export const REMOVE_ITEM = "REMOVE_ITEM"
export const CLEAR_CART = "CLEAR_CART"
export const CALC_CART = "CALC_CART"